*ECO 528
Project 1-3

Beta coefficients 
The security returns are generated by the following equations  
Ri = α + βRm + εi
; 


*See the IBM and AAPL data;
proc print data = ECO528_1.IBM;
run;
proc print data = ECO528_1.AAPL;
run;

*Examine the β coefficients for IBM and AAPL;
proc reg data = ECO528_1.IBM;
model ret = sprtrn;
run;

proc reg data = ECO528_1.AAPL;
model ret = sprtrn;
run;
